version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

references:
  yarn-cache-key-latest: &yarn-cache-key-latest
    v1-dependency-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}-latest
  yarn-cache-key: &yarn-cache-key
    v1-dependency-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
  yarn-backup-cache-key: &yarn-backup-cache-key
    v1-dependency-yarn-{{ .Branch }}-
  yarn-backup-cache-key-no-branch: &yarn-backup-cache-key-no-branch
    v1-dependency-yarn-

  node-14: &node-14
    cimg/node:14.21.1
  node-16: &node-16
    cimg/node:16.19.0
  node-18: &node-18
    cimg/node:18.13.0

  node-14-latest: &node-14-latest
    cimg/node:14.21.1
  node-16-latest: &node-16-latest
    cimg/node:16.19.0
  node-18-latest: &node-18-latest
    cimg/node:18.13.0



commands:
  install-dependencies:
    steps:
      - run:
          name: Yarn version
          command: yarn --version
      - restore_cache:
          keys:
            - *yarn-cache-key
            - *yarn-backup-cache-key
            - *yarn-backup-cache-key-no-branch
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn package cache
          key: *yarn-cache-key
          paths:
            - ~/.cache/yarn

  install-dependencies-latest:
    steps:
      - run:
          name: Yarn version
          command: yarn --version
      - restore_cache:
          keys:
            - *yarn-cache-key-latest
            - *yarn-cache-key
            - *yarn-backup-cache-key
            - *yarn-backup-cache-key-no-branch
      - run:
          name: Upgrade dependencies lockfile and install
          command: yarn upgrade
      - run:
          name: Output dependencies diff
          command: git --no-pager diff
      - save_cache:
          name: Save yarn package cache
          key: *yarn-cache-key-latest
          paths:
            - ~/.cache/yarn

  checks:
    steps:
      - run:
          name: Lint Typescript code
          command: yarn lint
      - run:
          name: Audit production dependencies
          command: yarn audit-dependencies

  build:
    steps:
      - run:
          name: Build project
          command: yarn build

  tests:
    steps:
      - run:
          name: TS Unit tests
          command: yarn test:coverage
      - run:
          name: Test documentation snippets
          command: yarn test:snippets
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: ~/test-results/

jobs:
  checks:
    docker:
      - image: *node-18
    steps:
      - checkout
      - install-dependencies
      - checks

  test-node-14:
    docker:
      - image: *node-14
    steps:
      - checkout
      - install-dependencies
      - build
      - tests

  test-node-16:
    docker:
      - image: *node-16
    steps:
      - checkout
      - install-dependencies
      - build
      - tests

  test-node-18:
    docker:
      - image: *node-18
    steps:
      - checkout
      - install-dependencies
      - build
      - tests
      - coveralls/upload

  checks-latest:
    docker:
      - image: *node-18
    steps:
      - checkout
      - install-dependencies-latest
      - checks

  test-node-14-latest:
    docker:
      - image: *node-14-latest
    steps:
      - checkout
      - install-dependencies-latest
      - build
      - tests

  test-node-16-latest:
    docker:
      - image: *node-16-latest
    steps:
      - checkout
      - install-dependencies-latest
      - build
      - tests

  test-node-18-latest:
    docker:
      - image: *node-18-latest
    steps:
      - checkout
      - install-dependencies-latest
      - build
      - tests

workflows:
  version: 2
  test:
    jobs:
      - checks
      - test-node-14
      - test-node-16
      - test-node-18

  weekly:
    jobs:
      - checks-latest
      - test-node-14-latest
      - test-node-16-latest
      - test-node-18-latest
    triggers:
      - schedule:
          # Midnight on Sunday
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - main
